default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure a clean state
    # git_pull
    
    # Setup certificates
    match(type: "appstore")
    
    increment_build_number(
      build_number: lane_context[SharedValues::BUILD_NUMBER]
    )
    
    build_app(
      scheme: "MinMax",
      workspace: "MinMax.xcworkspace"
    )
    
    upload_to_testflight
  end
end

platform :android do
  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    # increment_version_code
    
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    
    upload_to_play_store(
      track: 'internal',
      track_promote_release_status: 'completed'
    )
  end
end
